/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    '/Users/karanveersingh/Downloads/Catalog-Prototype/public/**/*.html',
    '/Users/karanveersingh/Downloads/Catalog-Prototype/public/**/*.js',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#241911',
        'inverse-primary': '#ffb3ac',
        'surface-container-high': '#ece7e1',
        tertiary: '#3b2e25',
        'on-surface-variant': '#58413f',
        'surface-container-highest': '#e7e2db',
        'secondary-container': '#f0dfd8',
        'outline-variant': '#e0bfbc',
        'on-error-container': '#93000a',
        'on-primary-fixed-variant': '#8a1a1a',
        'tertiary-fixed-dim': '#d7c3b5',
        'tertiary-container': '#52443a',
        background: '#fef9f1',
        'surface-dim': '#ded9d3',
        'surface-container-low': '#f8f3ec',
        'primary-fixed': '#ffdad6',
        'primary-fixed-dim': '#ffb3ac',
        outline: '#8c716e',
        'on-background': '#1d1b17',
        'on-tertiary-fixed-variant': '#52443a',
        'tertiary-fixed': '#f4ded0',
        'error-container': '#ffdad6',
        'surface-container': '#f2ede6',
        'on-primary': '#ffffff',
        'on-secondary-container': '#6e625c',
        'on-secondary-fixed-variant': '#4f453f',
        'surface-container-lowest': '#ffffff',
        surface: '#fef9f1',
        'on-secondary-fixed': '#221a16',
        'on-surface': '#1d1b17',
        'primary-container': '#8b1a1a',
        error: '#ba1a1a',
        'inverse-on-surface': '#f5f0e9',
        'surface-variant': '#e7e2db',
        primary: '#690008',
        'on-primary-fixed': '#410003',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'inverse-surface': '#32302c',
        'secondary-fixed': '#f0dfd8',
        'secondary-fixed-dim': '#d3c3bc',
        'on-primary-container': '#ff9a91',
        'surface-tint': '#ac322e',
        'on-tertiary': '#ffffff',
        'surface-bright': '#fef9f1',
        'on-tertiary-container': '#c6b2a4',
        secondary: '#685c56',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        serif: ['Newsreader', 'serif'],
        sans: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
